name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Deploy to GitHub Pages
        env:
          MY_EMAIL: iigmir@gmail.com
          MY_NAME: iigmir
        run: |
          git config --global user.email $MY_EMAIL
          git config --global user.name $MY_NAME
          git remote set-url origin $MY_NAME:${{ secrets.MY_PASSWORD }}@github.com:iigmir/test_frontend.git
          npm run build
          gh-pages -d docs -u ${MY_NAME} <${MY_EMAIL}>
